### ISSUE TITLE
Need a post that mirrors the meetup and adds a schedule

### ISSUE THREAD

**Issue by patricia-gallardo** [tech-women/tech-women.github.io#1]
Basically something like this 
https://www.meetup.com/Tech-Women-Norway/events/264108718/
- so take the picture and the text - and make a post - then we need to make a nice table or something with the schedule, which is something like this:

08.20 - 9:00 : breakfast + mingling
9:00 Keynote
9:20 Speaker 1
9:40 Speaker 2
10:00 Break
10:10 Speaker 3
10:30 Speaker 4
10:50 Speaker 5
11:10 Break
11:20 Speaker 6
11:40 Speaker 7
12:00 Presentation of Role Models 2019
12:20 - 13:00 Lunch

**Comment by coderbyheart** [comment]
Do you have an un-cropped version of the logo?

**Comment by patricia-gallardo** [comment]
Yes! They are all here: https://github.com/tech-women/tech-women.github.io/tree/master/assets/images

**Comment by patricia-gallardo** [comment]
We really need to put up a schedule somewhere, if you don't have time, I can try to do it on Monday.

**Comment by patricia-gallardo** [comment]
![2019-08-26 13 09 27 127 0 0 1 b2e03e49aceb](https://user-images.githubusercontent.com/25172913/63686672-c3ae9880-c802-11e9-825c-0493f6a668b0.jpg)

When I spin it up locally the nomination button is just the html text - I'll merge it and see if it was just a local thing.

**Comment by patricia-gallardo** [comment]
Thank you so much, Markus!

**Comment by patricia-gallardo** [comment]
https://twitter.com/TechWomenNorway/status/1165986472983482368
