### ISSUE TITLE
Link Code of Conduct

### ISSUE THREAD

**Issue by coderbyheart** [tech-women/tech-women.github.io#10]
@patricia-gallardo I noticed that the page has no Code of Conduct and then I found https://github.com/tech-women/code-of-conduct ... I propose to adapt this code of conduct.

It's especially important to provide contact information during the event, so we need to add/replace: 

- [ ] a phone number, an email, a Slack channel which is monitored during the event
- [ ] either individuals or a group of people (e.g. "the organizers, who wear a yellow t-shirt") who can be approached in case of Code of Conduct violations

**Comment by patricia-gallardo** [comment]
Yes! Of course!

**Comment by patricia-gallardo** [comment]
I made it waaay in the beginning - before the site - so I forgot
