### ISSUE TITLE
Ada: speaker info and sponsor logos

### ISSUE THREAD

**Issue by coderbyheart** [tech-women/tech-women.github.io#4]
@patricia-gallardo I'd like to add speaker info (name, picture, URL) as soon as it is available, and also think that it would be nice to display sponsor logos.

What do you think?

## Speakers

- [x] https://twitter.com/siljel
- [x] https://twitter.com/acdlola
- [x] https://twitter.com/tannaznvr
- [x] https://twitter.com/siljelb
- [x] https://twitter.com/a_meba
- [ ] https://twitter.com/ChristinGorman

**Comment by patricia-gallardo** [comment]
Sponsor logos are great - and so is speaker info... maybe they should be in some kind of folder so that we have a structure for future events?

Currently I don't have bios for them though - or pictures :smile: 

But I'm trying to fill in the agenda.

**Comment by coderbyheart** [comment]
Yes, I can arrange that so that we move to a per-year basis. 

If you send me the the contact details of the speakers (via email, Twitter PN, ...) I can reach out to them and collect that information.

**Comment by patricia-gallardo** [comment]
For the confirmed speakers their names in the agenda now link to their twitter accounts - one thing to ask them is what they want us to link to - twitter is good for getting people to follow them, but maybe multiple things would be nice? Like in the authors page? Maybe we can have icons after their names?
![2019-08-27 22 34 01 techwomen no 8d883eba4cf8](https://user-images.githubusercontent.com/25172913/63805928-c9979d00-c91a-11e9-86dd-008a4da13d4f.jpg)

**Comment by patricia-gallardo** [comment]
Or maybe that belongs in the speakers profile page...

**Comment by coderbyheart** [comment]
Sponsor logos added via https://github.com/tech-women/tech-women.github.io/pull/6

**Comment by coderbyheart** [comment]
I've added the first speaker: https://techwomen.no/speakers/lorena-carthy

Btw, I asked for pronouns, they appear on the speaker page and on the schedule.

**Comment by patricia-gallardo** [comment]
Omg! That's fantastic!!!

**Comment by coderbyheart** [comment]
@patricia-gallardo Could you reach out to Christin Gorman and Marta Paciorkowska and ask them if they could provide their profile information? I tried that via Twitter, but they did not yet reply.

    We kindly ask you to provide your speaker information for the
    Ada Lovelace Mini Conference.
    The content will be published on https://techwomen.no and you
    can always update it yourself later via 
    https://github.com/tech-women/tech-women.github.io/

    Here is an example entry: https://techwomen.no/speakers/silje-ljosland-bakke  

    Thank you!

    Name: 
    Pronouns:
    URLs (we can support multiple):
    Description (in third person, Markdown is supported):
    Image:

**Comment by patricia-gallardo** [comment]
Done, I'll forward it to you when I get it.

**Comment by coderbyheart** [comment]
Closing for now, for Christin I have linked to her article.
