### ISSUE TITLE
We probably should scale down some/all of the images to make the page load smoother

### ISSUE THREAD

**Issue by patricia-gallardo** [tech-women/tech-women.github.io#7]
Or maybe there is some nice fancy jekyll thing that can do that for us on the fly?
Or maybe I'm totally wrong :laughing:

**Comment by coderbyheart** [comment]
No, jekyll [can do that](https://github.com/zroger/jekyll-minimagick), but that plugin [is not supported by GitHub pages](https://pages.github.com/versions/).

However, once [GitHub Actions](https://github.com/features/actions) is available for this organization we can automatically commit scaled versions of all images.

For now we can either manually provide resized versions, or use a Content Management System like [Contentful](https://www.contentful.com/developers/docs/references/images-api/) or [Sanity](https://www.sanity.io/docs/asset-pipeline) which have image processing pipelines and are free to use for a small project like this.

**Comment by patricia-gallardo** [comment]
I got access to Actions a few days ago... Can I add it to this repo? I don't know how it works though

**Comment by patricia-gallardo** [comment]
Looks like it is only on my own repos -_-

**Comment by patricia-gallardo** [comment]
I like Jekyll and markdown - so I'd like to keep it as it is - so either we wait for actions or manually scale

**Comment by coderbyheart** [comment]
You should be able to sign up the org here: https://github.com/features/actions/

It might take a while until it is available.

**Comment by coderbyheart** [comment]
Run this when adding new images, to automatically create the thumbnails

    npm ci
    node resize-images.js

I have updated the template to automatically use the resized versions.
