### ISSUE TITLE
The profile pages should have a link or follow button to the profiled persons twitter

### ISSUE THREAD

**Issue by patricia-gallardo** [tech-women/tech-women.github.io#8]
Possibly to other things too, like linkedin and blog etc

**Comment by coderbyheart** [comment]
![Screenshot_20190901_122219](https://user-images.githubusercontent.com/188915/64075024-2ac0c700-ccb3-11e9-8c6c-a30f27508c4c.png)

Isn't that already there?
https://techwomen.no/author-patricia

**Comment by patricia-gallardo** [comment]
Those are for the "author" but I'd like a way to promote the profiled person, example here with Lotte:
https://techwomen.no/lotte-johansen-ux-for-everyone/

I want links to Lottes Twitter/LinkedIn/blog/etc

**Comment by coderbyheart** [comment]
I see, I added support for LinkedIn on speaker pages, e.g.: https://techwomen.no/speakers/silje-ljosland-bakke

I can add the same as a feature of the post layout, in a section at the bottom:

    More about <person> on the web:
    - Twitter
    - LinkedIn
    ...

What are her links?

**Comment by patricia-gallardo** [comment]
This is Lottes twitter at least: https://twitter.com/lotte_johansen

**Comment by coderbyheart** [comment]
In cc46253bb3730aa20786b332c154b1d31452fe43 I added the option to provide this block with various links.

**Comment by coderbyheart** [comment]
![Screenshot_20190910_103139](https://user-images.githubusercontent.com/188915/64597504-32205880-d3b6-11e9-88c2-629fa413be53.png)
